name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm install
        working-directory: ./travel-memories-app  # Cambia in ./ se in root, o il nome della tua sottocartella

      - name: Capacitor Add Android
        run: npx cap add android
        working-directory: ./travel-memories-app  # Stesso qui

      - name: Capacitor Sync
        run: npx cap sync android
        working-directory: ./travel-memories-app  # Stesso qui

      - name: Build Debug APK
        working-directory: ./travel-memories-app/android  # Aggiusta se sottocartella
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./travel-memories-app/android/app/build/outputs/apk/debug/app-debug.apk  # Aggiusta path

      - name: Build Release APK
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./travel-memories-app/android  # Aggiusta
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app.keystore
          echo "storeFile=app.keystore" > keystore.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
          ./gradlew assembleRelease

      - name: Upload Release APK
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./travel-memories-app/android/app/build/outputs/apk/release/app-release.apk  # Aggiusta path
