name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm install
        working-directory: .  # Esegui nella root del progetto

      - name: Capacitor Add Android
        run: npx cap add android
        working-directory: .  # Esegui nella root

      - name: Capacitor Sync
        run: npx cap sync android
        working-directory: .  # Esegui nella root

      - name: Build Debug APK
        working-directory: ./android  # Esegui dentro android/ (relativo alla root)
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk  # Path relativo alla root

      - name: Build Release APK
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./android  # Esegui dentro android/
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app.keystore
          echo "storeFile=app.keystore" > keystore.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >>
